# Generated by Django 5.1.6 on 2026-06-19 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteintake',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste_management.supplier'),
        ),
        migrations.AlterField(
            model_name='wastepurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
