# Generated by Django 5.1.6 on 2026-06-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.department'),
        ),
    ]
