# Generated by Django 5.1.6 on 2026-06-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_department_description_department_code'),
        ('finance', '0010_income_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
