# Generated by Django 5.1.6 on 2026-06-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('collection', 'Waste Collector'), ('hr', 'HR'), ('finance', 'Finance'), ('waste', 'Waste Management'), ('inventory', 'Inventory')], default='viewer', max_length=30),
        ),
    ]
